[workspace]
members = [
    "winbar",
    "winbar-plugin",
    "winbar-plugin-test",
    "winbarc",
    "winbar-core",
]
resolver = "2"

[workspace.package]
authors = ["Sulaxan"]
repository = "https://github.com/sulaxan/winbar"
license = "MIT"
edition = "2021"
